### ISSUE TITLE
NOT WORKING?

### ISSUE THREAD

**Issue by fanopolis** [strangerstudios/pmpro-cancel-on-next-payment-date#41] opened 2022-07-14 18:39 UTC
I have this plugin installed but it seems it's not working?

I have PMPro version 2.7.2.

When users cancel, their membership is canceled immediately instead of it being canceled at the end of the billing period. 

So basically this plugin is not working. Can someone confirm?

thanks

**Comment by mircobabini** [comment] 2022-07-14 19:43
The plugin is working. Can you please add some more details?
- which payment gateway are you using?
- are we talking of recurring levels?
- are users cancelling on site or from the gateway?

Thanks.

**Comment by fanopolis** [comment] 2022-07-14 21:14
Thanks for responding so fast Mirco. 

- I have both Stripe and Paypal Express.
- Yes, these are monthly reocurring subscriptions.

I'm looking at one case specifically. They canceled from the site, not the gateway. It was a stripe payment. What is strange is that I received two admin notification emails about the cancellation, at the same time. One has the correct date, but the other one has today's date. 

Thank you!

**Comment by mircobabini** [comment] 2022-07-15 17:48
Thanks for the insights.

Well, this is a known bug actually. I faced it too and already digged into it.

When you click the "cancel" button it takes some time for the page to reload and actually cancel the membership. Sometimes the users click the cancel button once again. The result is a double cancellation request.

They are almost concurrent but since there's no real concurrency here, they are subsequent.

1. The first one will cancel the membership by setting an expiration date ad expected.
2. The second one, sees the membership already cancelled with an expiration date set. Then, it completely cancel the membership. This is the exact line of code: https://github.com/strangerstudios/pmpro-cancel-on-next-payment-date/blob/dev/pmpro-cancel-on-next-payment-date.php#L81-L83

This is clearly an unwanted behaviour and the solution is made of two separate steps.

The first thing you want to do is to avoid double clicks on the cancel button.
This can be done via javascript by disabling the button as soon as clicked. I can provide a snippet for this.

Secondly we may want to add something, maybe a filter, to avoid complete cancellation.
I mean, with this "filter" set as true, I would expect to keep the membership until expiration date, no way to completely cancel it. This might also mean we don't want to show the "cancel" button anymore when the renewal is already cancelled.

This is something we internally discussed a few times. It's also reported in this draft PR: https://github.com/strangerstudios/pmpro-cancel-on-next-payment-date/pull/37

Let's keep @ideadude in the loop to see if we can come up with a complete solution here.

**Comment by fanopolis** [comment] 2022-07-15 20:56
Understood. Thank you very much.

Can you link me to that snippet, please?

**Comment by michaelbeil** [comment] 2022-07-19 21:09
@fanopolis This is a [gist](https://gist.github.com/mircobabini/10dbf809fb3c53cda7f84e4d7b268211) to avoid complete cancellation (https://github.com/strangerstudios/pmpro-cancel-on-next-payment-date/issues/16#issuecomment-1061839803).

**Comment by fanopolis** [comment] 2022-07-19 21:44
Thank you @michaelbeil ! Do I add it to functions.php or where?

**Comment by michaelbeil** [comment] 2022-07-19 22:50
You can add this recipe to your site by creating a custom plugin or using the Code Snippets plugin available for free in the WordPress repository. <a href="https://www.paidmembershipspro.com/create-a-plugin-for-pmpro-customizations/" target="_blank" rel="noopener noreferrer">Read this companion article for step-by-step directions on either method</a>. If you need further help, you can open a new ticket and we would be happy to provide you with assistance for this Add On in our [member support area](https://www.paidmembershipspro.com/new-topic/).

**Comment by kathleenfrank** [comment] 2022-08-17 17:06
I am having this same issue. @mircobabini What is the snippet to avoid double clicks on the cancel button?

**Comment by michaelbeil** [comment] 2022-08-17 18:05
@kathleenfrank This is the [gist](https://gist.github.com/mircobabini/10dbf809fb3c53cda7f84e4d7b268211) to avoid complete cancellation (mentioned [here](https://github.com/strangerstudios/pmpro-cancel-on-next-payment-date/issues/16#issuecomment-1061839803)). If you need further help, you can open a ticket in our [member support area](https://www.paidmembershipspro.com/new-topic/).

**Comment by ideadude** [comment] 2022-08-17 21:52
Duplicate of https://github.com/strangerstudios/pmpro-cancel-on-next-payment-date/issues/42

**Closed as completed by ideadude** 2022-08-17 21:52 UTC
Labels: bug
